name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!
        Please describe your idea clearly so we can evaluate it.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the motivation?
      placeholder: |
        I'm frustrated when...
        It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered?
      placeholder: Other solutions or workarounds...

  - type: dropdown
    id: scope
    attributes:
      label: Feature Scope
      description: What part of the application does this affect?
      options:
        - Editor / Text Editing
        - Terminal / Shell Integration
        - UI / Layout / Theming
        - Event System
        - Plugin / Extension System
        - Performance
        - Configuration
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority (your assessment)
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical / Blocking

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples.
      placeholder: Screenshots, links to similar features in other tools, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have read the project roadmap
          required: false
